import type { Metadata } from "next";
import { Header } from "../../component/header/Header";

import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <
      >
      <Header />
        {children}
      </>
  );
}
